name: Validate

on: [push, pull_request]

jobs:
  conftest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Conftest
        uses: redhat-cop/github-actions/confbatstest@master
        with:
          tests: _test/conftest.sh